(cl:defpackage controller_driver-msg
  (:use )
  (:export
   "<LEGMOVEACTION>"
   "LEGMOVEACTION"
   "<LEGMOVEACTIONFEEDBACK>"
   "LEGMOVEACTIONFEEDBACK"
   "<LEGMOVEACTIONGOAL>"
   "LEGMOVEACTIONGOAL"
   "<LEGMOVEACTIONRESULT>"
   "LEGMOVEACTIONRESULT"
   "<LEGMOVEFEEDBACK>"
   "LEGMOVEFEEDBACK"
   "<LEGMOVEGOAL>"
   "LEGMOVEGOAL"
   "<LEGMOVERESULT>"
   "LEGMOVERESULT"
  ))

