; Auto-generated. Do not edit!


(cl:in-package controller_driver-msg)


;//! \htmlinclude LegMoveGoal.msg.html

(cl:defclass <LegMoveGoal> (roslisp-msg-protocol:ros-message)
  ((target_positions
    :reader target_positions
    :initarg :target_positions
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0)))
)

(cl:defclass LegMoveGoal (<LegMoveGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LegMoveGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LegMoveGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name controller_driver-msg:<LegMoveGoal> is deprecated: use controller_driver-msg:LegMoveGoal instead.")))

(cl:ensure-generic-function 'target_positions-val :lambda-list '(m))
(cl:defmethod target_positions-val ((m <LegMoveGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader controller_driver-msg:target_positions-val is deprecated.  Use controller_driver-msg:target_positions instead.")
  (target_positions m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LegMoveGoal>) ostream)
  "Serializes a message object of type '<LegMoveGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'target_positions))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    ))
   (cl:slot-value msg 'target_positions))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LegMoveGoal>) istream)
  "Deserializes a message object of type '<LegMoveGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'target_positions) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'target_positions)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LegMoveGoal>)))
  "Returns string type for a message object of type '<LegMoveGoal>"
  "controller_driver/LegMoveGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LegMoveGoal)))
  "Returns string type for a message object of type 'LegMoveGoal"
  "controller_driver/LegMoveGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LegMoveGoal>)))
  "Returns md5sum for a message object of type '<LegMoveGoal>"
  "5318bcc8f490a8819c7cb865151f5d60")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LegMoveGoal)))
  "Returns md5sum for a message object of type 'LegMoveGoal"
  "5318bcc8f490a8819c7cb865151f5d60")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LegMoveGoal>)))
  "Returns full string definition for message of type '<LegMoveGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# LegMove.action~%# Goal~%int16[] target_positions  # 目标位置数组，单位为弧度~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LegMoveGoal)))
  "Returns full string definition for message of type 'LegMoveGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# LegMove.action~%# Goal~%int16[] target_positions  # 目标位置数组，单位为弧度~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LegMoveGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'target_positions) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LegMoveGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LegMoveGoal
    (cl:cons ':target_positions (target_positions msg))
))
