; Auto-generated. Do not edit!


(cl:in-package controller_driver-msg)


;//! \htmlinclude LegMoveFeedback.msg.html

(cl:defclass <LegMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((current_positions
    :reader current_positions
    :initarg :current_positions
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0)))
)

(cl:defclass LegMoveFeedback (<LegMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LegMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LegMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name controller_driver-msg:<LegMoveFeedback> is deprecated: use controller_driver-msg:LegMoveFeedback instead.")))

(cl:ensure-generic-function 'current_positions-val :lambda-list '(m))
(cl:defmethod current_positions-val ((m <LegMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader controller_driver-msg:current_positions-val is deprecated.  Use controller_driver-msg:current_positions instead.")
  (current_positions m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LegMoveFeedback>) ostream)
  "Serializes a message object of type '<LegMoveFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'current_positions))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    ))
   (cl:slot-value msg 'current_positions))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LegMoveFeedback>) istream)
  "Deserializes a message object of type '<LegMoveFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'current_positions) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'current_positions)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LegMoveFeedback>)))
  "Returns string type for a message object of type '<LegMoveFeedback>"
  "controller_driver/LegMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LegMoveFeedback)))
  "Returns string type for a message object of type 'LegMoveFeedback"
  "controller_driver/LegMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LegMoveFeedback>)))
  "Returns md5sum for a message object of type '<LegMoveFeedback>"
  "2a82a52ae14dfecd51d4d73c73f39b05")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LegMoveFeedback)))
  "Returns md5sum for a message object of type 'LegMoveFeedback"
  "2a82a52ae14dfecd51d4d73c73f39b05")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LegMoveFeedback>)))
  "Returns full string definition for message of type '<LegMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int16[] current_positions  # 当前关节位置数组，单位为弧度~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LegMoveFeedback)))
  "Returns full string definition for message of type 'LegMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int16[] current_positions  # 当前关节位置数组，单位为弧度~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LegMoveFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'current_positions) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LegMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LegMoveFeedback
    (cl:cons ':current_positions (current_positions msg))
))
