// Generated by gencpp from file controller_driver/LegMoveActionGoal.msg
// DO NOT EDIT!


#ifndef CONTROLLER_DRIVER_MESSAGE_LEGMOVEACTIONGOAL_H
#define CONTROLLER_DRIVER_MESSAGE_LEGMOVEACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <controller_driver/LegMoveGoal.h>

namespace controller_driver
{
template <class ContainerAllocator>
struct LegMoveActionGoal_
{
  typedef LegMoveActionGoal_<ContainerAllocator> Type;

  LegMoveActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  LegMoveActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::controller_driver::LegMoveGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LegMoveActionGoal_

typedef ::controller_driver::LegMoveActionGoal_<std::allocator<void> > LegMoveActionGoal;

typedef boost::shared_ptr< ::controller_driver::LegMoveActionGoal > LegMoveActionGoalPtr;
typedef boost::shared_ptr< ::controller_driver::LegMoveActionGoal const> LegMoveActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller_driver::LegMoveActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller_driver::LegMoveActionGoal_<ContainerAllocator1> & lhs, const ::controller_driver::LegMoveActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller_driver::LegMoveActionGoal_<ContainerAllocator1> & lhs, const ::controller_driver::LegMoveActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6b6fcb9b8281ffd5004276c4c371200";
  }

  static const char* value(const ::controller_driver::LegMoveActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6b6fcb9b8281ffdULL;
  static const uint64_t static_value2 = 0x5004276c4c371200ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller_driver/LegMoveActionGoal";
  }

  static const char* value(const ::controller_driver::LegMoveActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"LegMoveGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: controller_driver/LegMoveGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# LegMove.action\n"
"# Goal\n"
"int16[] target_positions  # 目标位置数组，单位为弧度\n"
;
  }

  static const char* value(const ::controller_driver::LegMoveActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegMoveActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_driver::LegMoveActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller_driver::LegMoveActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::controller_driver::LegMoveGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_DRIVER_MESSAGE_LEGMOVEACTIONGOAL_H
