// Generated by gencpp from file controller_driver/LegMoveGoal.msg
// DO NOT EDIT!


#ifndef CONTROLLER_DRIVER_MESSAGE_LEGMOVEGOAL_H
#define CONTROLLER_DRIVER_MESSAGE_LEGMOVEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller_driver
{
template <class ContainerAllocator>
struct LegMoveGoal_
{
  typedef LegMoveGoal_<ContainerAllocator> Type;

  LegMoveGoal_()
    : target_positions()  {
    }
  LegMoveGoal_(const ContainerAllocator& _alloc)
    : target_positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _target_positions_type;
  _target_positions_type target_positions;





  typedef boost::shared_ptr< ::controller_driver::LegMoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_driver::LegMoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LegMoveGoal_

typedef ::controller_driver::LegMoveGoal_<std::allocator<void> > LegMoveGoal;

typedef boost::shared_ptr< ::controller_driver::LegMoveGoal > LegMoveGoalPtr;
typedef boost::shared_ptr< ::controller_driver::LegMoveGoal const> LegMoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller_driver::LegMoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller_driver::LegMoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller_driver::LegMoveGoal_<ContainerAllocator1> & lhs, const ::controller_driver::LegMoveGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_positions == rhs.target_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller_driver::LegMoveGoal_<ContainerAllocator1> & lhs, const ::controller_driver::LegMoveGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller_driver::LegMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_driver::LegMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_driver::LegMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_driver::LegMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_driver::LegMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_driver::LegMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller_driver::LegMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5318bcc8f490a8819c7cb865151f5d60";
  }

  static const char* value(const ::controller_driver::LegMoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5318bcc8f490a881ULL;
  static const uint64_t static_value2 = 0x9c7cb865151f5d60ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_driver::LegMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller_driver/LegMoveGoal";
  }

  static const char* value(const ::controller_driver::LegMoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller_driver::LegMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# LegMove.action\n"
"# Goal\n"
"int16[] target_positions  # 目标位置数组，单位为弧度\n"
;
  }

  static const char* value(const ::controller_driver::LegMoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller_driver::LegMoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegMoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_driver::LegMoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller_driver::LegMoveGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_positions: ";
    if (v.target_positions.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_positions.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int16_t>::stream(s, true ? std::string() : indent + "    ", v.target_positions[i]);
    }
    if (v.target_positions.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_DRIVER_MESSAGE_LEGMOVEGOAL_H
