// Generated by gencpp from file controller_driver/LegMoveFeedback.msg
// DO NOT EDIT!


#ifndef CONTROLLER_DRIVER_MESSAGE_LEGMOVEFEEDBACK_H
#define CONTROLLER_DRIVER_MESSAGE_LEGMOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller_driver
{
template <class ContainerAllocator>
struct LegMoveFeedback_
{
  typedef LegMoveFeedback_<ContainerAllocator> Type;

  LegMoveFeedback_()
    : current_positions()  {
    }
  LegMoveFeedback_(const ContainerAllocator& _alloc)
    : current_positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _current_positions_type;
  _current_positions_type current_positions;





  typedef boost::shared_ptr< ::controller_driver::LegMoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_driver::LegMoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LegMoveFeedback_

typedef ::controller_driver::LegMoveFeedback_<std::allocator<void> > LegMoveFeedback;

typedef boost::shared_ptr< ::controller_driver::LegMoveFeedback > LegMoveFeedbackPtr;
typedef boost::shared_ptr< ::controller_driver::LegMoveFeedback const> LegMoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller_driver::LegMoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller_driver::LegMoveFeedback_<ContainerAllocator1> & lhs, const ::controller_driver::LegMoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_positions == rhs.current_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller_driver::LegMoveFeedback_<ContainerAllocator1> & lhs, const ::controller_driver::LegMoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_driver::LegMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_driver::LegMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_driver::LegMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a82a52ae14dfecd51d4d73c73f39b05";
  }

  static const char* value(const ::controller_driver::LegMoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a82a52ae14dfecdULL;
  static const uint64_t static_value2 = 0x51d4d73c73f39b05ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller_driver/LegMoveFeedback";
  }

  static const char* value(const ::controller_driver::LegMoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"int16[] current_positions  # 当前关节位置数组，单位为弧度\n"
"\n"
;
  }

  static const char* value(const ::controller_driver::LegMoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegMoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_driver::LegMoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller_driver::LegMoveFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "current_positions: ";
    if (v.current_positions.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.current_positions.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int16_t>::stream(s, true ? std::string() : indent + "    ", v.current_positions[i]);
    }
    if (v.current_positions.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_DRIVER_MESSAGE_LEGMOVEFEEDBACK_H
