// Generated by gencpp from file controller_driver/LegMoveResult.msg
// DO NOT EDIT!


#ifndef CONTROLLER_DRIVER_MESSAGE_LEGMOVERESULT_H
#define CONTROLLER_DRIVER_MESSAGE_LEGMOVERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller_driver
{
template <class ContainerAllocator>
struct LegMoveResult_
{
  typedef LegMoveResult_<ContainerAllocator> Type;

  LegMoveResult_()
    : success(false)
    , message()  {
    }
  LegMoveResult_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::controller_driver::LegMoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_driver::LegMoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct LegMoveResult_

typedef ::controller_driver::LegMoveResult_<std::allocator<void> > LegMoveResult;

typedef boost::shared_ptr< ::controller_driver::LegMoveResult > LegMoveResultPtr;
typedef boost::shared_ptr< ::controller_driver::LegMoveResult const> LegMoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller_driver::LegMoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller_driver::LegMoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller_driver::LegMoveResult_<ContainerAllocator1> & lhs, const ::controller_driver::LegMoveResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller_driver::LegMoveResult_<ContainerAllocator1> & lhs, const ::controller_driver::LegMoveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller_driver::LegMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller_driver::LegMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_driver::LegMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller_driver::LegMoveResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_driver::LegMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller_driver::LegMoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller_driver::LegMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::controller_driver::LegMoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_driver::LegMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller_driver/LegMoveResult";
  }

  static const char* value(const ::controller_driver::LegMoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller_driver::LegMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool success               # 指示动作是否成功完成\n"
"string message            # 结果消息，包含错误信息或成功确认\n"
;
  }

  static const char* value(const ::controller_driver::LegMoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller_driver::LegMoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegMoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_driver::LegMoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller_driver::LegMoveResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_DRIVER_MESSAGE_LEGMOVERESULT_H
