// Auto-generated. Do not edit!

// (in-package controller_driver.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LegMoveFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_positions = null;
    }
    else {
      if (initObj.hasOwnProperty('current_positions')) {
        this.current_positions = initObj.current_positions
      }
      else {
        this.current_positions = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LegMoveFeedback
    // Serialize message field [current_positions]
    bufferOffset = _arraySerializer.int16(obj.current_positions, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LegMoveFeedback
    let len;
    let data = new LegMoveFeedback(null);
    // Deserialize message field [current_positions]
    data.current_positions = _arrayDeserializer.int16(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 2 * object.current_positions.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'controller_driver/LegMoveFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2a82a52ae14dfecd51d4d73c73f39b05';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    int16[] current_positions  # 当前关节位置数组，单位为弧度
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LegMoveFeedback(null);
    if (msg.current_positions !== undefined) {
      resolved.current_positions = msg.current_positions;
    }
    else {
      resolved.current_positions = []
    }

    return resolved;
    }
};

module.exports = LegMoveFeedback;
